# Generated by Django 4.1.5 on 2023-10-03 13:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True,
                        default=None,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("price", models.CharField(max_length=100, null=True)),
                ("year", models.CharField(max_length=100, null=True)),
                ("origin", models.CharField(max_length=100, null=True)),
                ("registration_date", models.CharField(max_length=100, null=True)),
                ("technical_inspection", models.CharField(max_length=100, null=True)),
                ("first_hand", models.CharField(max_length=100, null=True)),
                ("mileage", models.CharField(max_length=100, null=True)),
                ("fuel_type", models.CharField(max_length=100, null=True)),
                ("transmission", models.CharField(max_length=100, null=True)),
                ("num_doors", models.CharField(max_length=100, null=True)),
                ("num_seats", models.CharField(max_length=100, null=True)),
                ("power", models.CharField(max_length=100, null=True)),
                ("co2_emission", models.CharField(max_length=100, null=True)),
                ("length", models.CharField(max_length=100, null=True)),
                ("critair_rating", models.CharField(max_length=100, null=True)),
                ("combined_consumption", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
