# Generated by Django 4.1.5 on 2023-10-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("price_pilot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="trunk_volume",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
